app:
  security:
    secret: ${AUTH_SECRET}
    salt: ${AUTH_SALT}
  default-users:
    admin:
      username: ${DEFAULT_ADMIN_USERNAME:}
      password: ${DEFAULT_ADMIN_PASSWORD:}
    user:
      username: ${DEFAULT_USER_USERNAME:}
      password: ${DEFAULT_USER_PASSWORD:}

spring:
  data:
    mongodb:
      host: localhost
      port: 27019
      database: auth_db
      username: mongoadmin
      password: password
      uuid-representation: standard
      authentication-database: admin
      auto-index-creation: true

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
